//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSide.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ImportShipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportShipment()
        {
            setDefaultValue();
        }
        public int ImportShipmentID { get; set; }
        public Nullable<System.DateTime> importDate { get; set; }
        public string productID { get; set; }

        [Required(ErrorMessage = "Cần nhập dữ liệu")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Giá nhập không được có ký tự")]
        public double importPrice { get; set; }


        [Required(ErrorMessage = "Cần nhập dữ liệu")]
        public int quantity { get; set; }

        public virtual Product Product { get; set; }

        public void setDefaultValue()
        {
            importDate = DateTime.Now;
        }
    }
}