//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSide.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ImportShipments = new HashSet<ImportShipment>();
            setDefaultValue();
        }

        public string productID { get; set; }
        public int subcategoryID { get; set; }
        public int supplierID { get; set; }

        [Required(ErrorMessage = "Cần nhập dữ liệu")]
        public string productName { get; set; }

        [Required(ErrorMessage = "Cần nhập dữ liệu")]
        public string productDescription { get; set; }

        public string productFeedback { get; set; }
        public int productRate { get; set; }

        [Required(ErrorMessage = "Cần nhập dữ liệu")]
        public string productSize { get; set; }

        [Required(ErrorMessage = "Cần nhập dữ liệu")]
        [RegularExpression(@"^[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\s\W|_]+$",
                            ErrorMessage = "Chỉ nhập chữ!")]
        public string productColor { get; set; }

        //[Required(ErrorMessage = "Cần nhập dữ liệu")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Giá bán không được có ký tự")]
        public Nullable<double> exportPrice { get; set; }

        public string productIcon { get; set; }
        public string productStatus { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual Supplier Supplier { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportShipment> ImportShipments { get; set; }

        public void setDefaultValue()
        {
            productRate = 0;
            productStatus = "Active";
        }
    }
}