//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingInfor
    {
        public int shipID { get; set; }
        public int orderID { get; set; }
        public string shipPhone { get; set; }
        public string address { get; set; }
        public string shipName { get; set; }
        public string dateShip { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
