//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSide.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Products = new HashSet<Product>();
        }

        public int supplierID { get; set; }

        [Required(ErrorMessage = "Không được để trống ô nhập")]
        public string supplierName { get; set; }

        [Required(ErrorMessage = "Không được để trống ô nhập")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Nhập không đúng format. VD: abc@xyz.com")]
        public string email { get; set; }

        [Required(ErrorMessage = "Không được để trống ô nhập")]
        [RegularExpression(@"(09|08|03|07|05)+([0-9]{8})\b", ErrorMessage = "Số điện thoại không đúng format")]
        public string phone { get; set; }

        [Required(ErrorMessage = "Không được để trống ô nhập")]
        public string address { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}