//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerSide.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
            setDefaultValue();
        }

        public int userID { get; set; }
        public int typeID { get; set; }
        [Required(ErrorMessage = "Không được để trống ô nhập")]
        public string username { get; set; }

        [Required(ErrorMessage = "Không được để trống ô nhập")]
        public string password { get; set; }

        [Required(ErrorMessage = "Không được để trống ô nhập")]
        [RegularExpression(@"^[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạ
ảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜ
ỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\s\W|_]+$", ErrorMessage = "Chỉ nhập chữ!")]
        public string fullname { get; set; }


        public string address { get; set; }

        [Required(ErrorMessage = "Không được để trống ô nhập")]
        [RegularExpression(@"(09|08|03|07|05)+([0-9]{8})\b", ErrorMessage = "Số điện thoại không đúng format")]
        public string phone { get; set; }

        [Required(ErrorMessage = "Không được để trống ô nhập")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Nhập không đúng format. VD: abc@xyz.com")]
        public string email { get; set; }

        [Required(ErrorMessage = "Không được để trống ô nhập")]
        public string gender { get; set; }

        [Required(ErrorMessage = "Không được để trống ô nhập")]
        [RegularExpression(@"^([0-2][0-9]|(3)[0-1])(\/)(((0)[0-9])|((1)[0-2]))(\/)\d{4}$", ErrorMessage = "Không đúng định dạng ngày")]
        public string birthday { get; set; }
        public string registerDate { get; set; }
        public string status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }

        public virtual UserType UserType { get; set; }

        public void setDefaultValue()
        {
            registerDate = DateTime.Now.ToString();
            status = "Active";
        }
    }
}