//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSites.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportShipment
    {
        public int ImportShipmentID { get; set; }
        public Nullable<System.DateTime> importDate { get; set; }
        public string productID { get; set; }
        public Nullable<double> importPrice { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
