//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSites.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderDetailID { get; set; }
        public Nullable<int> orderID { get; set; }
        public string productName { get; set; }
        public Nullable<int> productQuantityOrder { get; set; }
        public Nullable<double> productTotalPrice { get; set; }
        public string productID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
