//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSites.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ImportShipments = new HashSet<ImportShipment>();
            this.Ratings = new HashSet<Rating>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public string productID { get; set; }
        public int subcategoryID { get; set; }
        public int supplierID { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public string productFeedback { get; set; }
        public Nullable<int> productRate { get; set; }
        public string productSize { get; set; }
        public string productColor { get; set; }
        public Nullable<double> exportPrice { get; set; }
        public string productStatus { get; set; }
        public string productIcon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportShipment> ImportShipments { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}
