//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreSites.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int cartID { get; set; }
        public int userID { get; set; }
        public string productID { get; set; }
        public int productQuantityOrder { get; set; }
        public double productTotalPrice { get; set; }
        public double productPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
